package `fun`.sandstorm.ui.gallery

import `fun`.sandstorm.R

//TODO: Move to the model package
class Overlays {

    val drawableFromName = mapOf(
        "watermark" to R.drawable.watermark,
        "roto" to R.drawable.roto,
        "ic_launcher_foreground" to R.mipmap.ic_launcher_foreground,
        "alfredo" to R.drawable.alfredo,
        "pepelaugh" to R.drawable.pepelaugh,
        "pogchamp" to R.drawable.pogchamp,
        "weirdchamp" to R.drawable.weirdchamp,
        "alfredo" to R.drawable.alfredo,
        "emoji_dyrhaug_13" to R.drawable.emoji_dyrhaug_13,
        "emoji_dyrhaug_22" to R.drawable.emoji_dyrhaug_22,
        "gun" to R.drawable.gun,
        "heart" to R.drawable.heart,
        "heart2" to R.drawable.heart2,
        "headgear_9" to R.drawable.headgear_9,
        "headgear_10" to R.drawable.headgear_10,
        "headgear_11" to R.drawable.headgear_11,
        "headgear_12" to R.drawable.headgear_12,
        "headgear_13" to R.drawable.headgear_13,
        "headgear_14" to R.drawable.headgear_14,
        "headgear_17" to R.drawable.headgear_17,
        "headgear_19" to R.drawable.headgear_19,
        "headgear_20" to R.drawable.headgear_20,
        "headgear_24" to R.drawable.headgear_24,
        "headgear_25" to R.drawable.headgear_25,
        "headgear_26" to R.drawable.headgear_26,
        "headgear_27" to R.drawable.headgear_27,
        "headgear_28" to R.drawable.headgear_28,
        "headgear_29" to R.drawable.headgear_29,
        "headgear_30" to R.drawable.headgear_30,
        "headgear_31" to R.drawable.headgear_31,
        "headgear_32" to R.drawable.headgear_32,
        "headgear_41" to R.drawable.headgear_41,
        "headgear_42" to R.drawable.headgear_42,
        "headgear_43" to R.drawable.headgear_43,
        "headgear_45" to R.drawable.headgear_45,
        "headgear_56" to R.drawable.headgear_56,
        "headgear_57" to R.drawable.headgear_57,
        "roto" to R.drawable.roto,
        "speech_ballon" to R.drawable.speech_ballon,
        "star" to R.drawable.star,
        "sticker_bullet_hole_glass" to R.drawable.sticker_bullet_hole_glass,
        "sticker_bullet_hole_glass2" to R.drawable.sticker_bullet_hole_glass2,
        "trump_hair" to R.drawable.trump_hair,
        "compassion" to R.drawable.compassion,
        "dewit" to R.drawable.dewit,
        "huh" to R.drawable.huh,
        "kalm" to R.drawable.kalm,
        "manningface" to R.drawable.manningface,
        "okboomer" to R.drawable.okboomer,
        "oke" to R.drawable.oke,
        "panik" to R.drawable.panik,
        "trumphappy" to R.drawable.trumhappy,
        "trumpkiss" to R.drawable.trumpkiss,
        "whatthe" to R.drawable.whatthe,
        "pikawhat" to R.drawable.pikawat,
        "catree" to R.drawable.catree,
        "conceitedreaction" to R.drawable.conceitedreaction,
        "cringeharold" to R.drawable.cringeharold,
        "dude" to R.drawable.dude,
        "margekrump" to R.drawable.margekrump,
        "squiddab" to R.drawable.squiddab,
        "unsettledtom" to R.drawable.unsettledtom,
        "politecat" to R.drawable.politecat,
        "elon" to R.drawable.elon,
        "drakeyes" to R.drawable.drakeyes,
        "kanye" to R.drawable.kanye,
        "noanime" to R.drawable.noanime,
        "putinsmile" to R.drawable.putinsmile,
        "headgear_5" to R.drawable.headgear_5,
        "headgear_6" to R.drawable.headgear_6,
        "headgear_7" to R.drawable.headgear_7


    )
}